<?php
return [
    'up' => "CREATE TABLE IF NOT EXISTS products (
        id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
        product_code VARCHAR(50) NOT NULL UNIQUE,
        name VARCHAR(255) NOT NULL,
        subtitle VARCHAR(255) DEFAULT NULL,
        price DECIMAL(10,2) NOT NULL,
        original_price DECIMAL(10,2) DEFAULT NULL,
        category_key VARCHAR(50) NOT NULL,
        sub_category VARCHAR(150) DEFAULT NULL,
        description TEXT,
        details JSON DEFAULT NULL,
        fabric VARCHAR(255) DEFAULT NULL,
        fit VARCHAR(255) DEFAULT NULL,
        sizes JSON DEFAULT NULL,
        colors JSON DEFAULT NULL,
        images JSON DEFAULT NULL,
        is_new TINYINT(1) NOT NULL DEFAULT 0,
        is_best_seller TINYINT(1) NOT NULL DEFAULT 0,
        is_sale TINYINT(1) NOT NULL DEFAULT 0,
        in_stock TINYINT(1) NOT NULL DEFAULT 1,
        featured_in_lookbook TINYINT(1) NOT NULL DEFAULT 0,
        rating DECIMAL(2,1) NOT NULL DEFAULT 5.0,
        review_count INT UNSIGNED NOT NULL DEFAULT 0,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        CONSTRAINT fk_products_category FOREIGN KEY (category_key) REFERENCES categories(category_key) ON UPDATE CASCADE
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
    'down' => 'DROP TABLE IF EXISTS products',
];
